### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pratik-mk** [pratik-mk/streaming-service-typescript#4]
- [ ]  search into search not working
- [ ]  empty search handle
- [ ]  CSS improve
- [ ]  Series integration
- [ ]  Player page improve 
- [ ]  Pagination on Search Page
